version: "3"
services:
  sudoku-app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    volumes: 
      - /sudoku/sudoku-react/node_modules
      - ./sudoku-react:/sudoku/sudoku-react     