export const GRID_SIZE = 9;
export const EMPTY_VALUE = 0;
export const REMOVE_NUMBERS_COUNT = 32;
export const REMOVE_NUMBERS_COUNT_EASY = 32;
export const REMOVE_NUMBERS_COUNT_MEDIUM = 40;
export const REMOVE_NUMBERS_COUNT_HARD = 45;
export const REMOVE_NUMBERS_COUNT_EXPERT = 50;
export const NUMBERS = ['1', '2', '3', '4', '5', '6', '7', '8', '9'];
export const difficultyLevels: ['easy', 'medium', 'hard', 'expert'] = ['easy', 'medium', 'hard', 'expert'];
