export const GRID_SIZE = 9;
export const EMPTY_VALUE = 0;
export const REMOVE_NUMBERS_COUNT = 32;
export const ATTEMPT_EASY = 3;
export const ATTEMPT_MEDIUM = 4;
export const ATTEMPT_HARD = 5;
export const ATTEMPT_EXPERT = 10;
export const NUMBERS = ['1', '2', '3', '4', '5', '6', '7', '8', '9'];
export const difficultyLevels: ['easy', 'medium', 'hard', 'expert'] = ['easy', 'medium', 'hard', 'expert'];
